### ISSUE TITLE
为什么我无法运行项目？

### ISSUE THREAD

**Issue by stvenzyl** [ysk2014/webshell#1]
为什么我无法运行项目？

**Comment by ysk2014** [comment]
先进行安装，否则没有办法跑，依赖项分为前端和node，都需要安装
```
npm install
npm run dev

cd assets

npm install

npm start
```

**Comment by wangqiaoqiaogithub** [comment]
关于node-pty在mac下报错不知如何安装才能使node服务端中的代码跑起来
以下报错，小白求指导
![屏幕快照 2019-12-31 上午11 31 54](https://user-images.githubusercontent.com/40631098/71609151-3967ae00-2bc1-11ea-93c8-7fadb6533200.png)

**Comment by wangqiaoqiaogithub** [comment]
@ysk2014

**Comment by wangqiaoqiaogithub** [comment]
关于node-pty在mac下报错不知如何安装才能使node服务端中的代码跑起来
以下报错，小白求指导 @ysk2014 
![屏幕快照 2019-12-06 下午9 38 39](https://user-images.githubusercontent.com/40631098/71609278-21445e80-2bc2-11ea-9ac2-737844db957b.png)

**Comment by wangqiaoqiaogithub** [comment]
关于node-pty在mac下报错不知如何安装才能使node服务端中的代码跑起来
以下报错，小白求指导 @ysk2014 
![屏幕快照 2019-12-06 下午9 38 39](https://user-images.githubusercontent.com/40631098/71609293-37eab580-2bc2-11ea-88aa-b16b05ba91b2.png)

**Comment by wangqiaoqiaogithub** [comment]
关于node-pty在mac下报错不知如何安装才能使node服务端中的代码跑起来
以下报错，小白求指导 @ysk2014 
![屏幕快照 2019-12-06 下午9 38 39](https://user-images.githubusercontent.com/40631098/71609312-551f8400-2bc2-11ea-9fdd-5d85b9df219e.png)

**Comment by wangqiaoqiaogithub** [comment]
关于node-pty在mac下报错不知如何安装才能使node服务端中的代码跑起来
以下报错，小白求指导 @ysk2014 
![屏幕快照 2019-12-31 上午11 41 28](https://user-images.githubusercontent.com/40631098/71609335-88faa980-2bc2-11ea-9690-021d73b066c0.png)

**Comment by ysk2014** [comment]
@wangqiaoqiaogithub 现在用的node-pty:V0.8.1在node版本为12会有问题，你更新下node-pty版本试试

**Comment by wangqiaoqiaogithub** [comment]
@ysk2014  在windows的nodev12.13.1下会显示这个错误，希望作者看到处理下:exclamation:
![21577780969_ pic_hd](https://user-images.githubusercontent.com/40631098/71615359-dc352200-2beb-11ea-9f81-f84ccb57208d.jpg)

**Comment by wangqiaoqiaogithub** [comment]
@ysk2014 在windows的nodev12.13.1下会显示这个错误，希望作者看到处理下:exclamation:
![21577780969_ pic_hd](https://user-images.githubusercontent.com/40631098/71615420-3c2bc880-2bec-11ea-98a5-60f51793b597.jpg)

**Comment by ysk2014** [comment]
@wangqiaoqiaogithub 麻烦描述下出现错误的场景

**Comment by wangqiaoqiaogithub** [comment]
@ysk2014 克隆该项目并按照官网上给出的node-pty下的windows安装解决方案后npm run dev就会出现这种错误

**Comment by wangqiaoqiaogithub** [comment]
@ysk2014 克隆该项目并按照官网上给出的node-pty下的windows安装解决方案后npm run dev启动开发环境就会出现这种错误，npm i 倒是正常执行

**Comment by stvenzyl** [comment]
> 先进行安装，否则没有办法跑，依赖项分为前端和node，都需要安装
> 
> ```
> npm install
> npm run dev
> 
> cd assets
> 
> npm install
> 
> npm start
> ```

好多，谢谢
